#!/usr/bin/env python3
"""Generate .claude/docs/CODE_MAP.md — a low-token map of what each module does.

Deterministic and stdlib-only (no LLM — ADR-001): walks the project's Python
sources via the `ast` module and emits, per file, the module docstring's first
line plus each public class/function with the first line of its docstring.

Agents read this map FIRST to learn "what does what" instead of grepping and
reading every file — the map is a fraction of the source size, so it answers
structural questions at a fraction of the tokens. Regenerate it whenever the
public API changes (`just code-map`, or call this directly).

Usage:
    python .claude/scripts/gen_code_map.py [root]   # default root: cwd
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

SKIP_DIRS = {
    ".venv",
    "venv",
    "env",
    "__pycache__",
    ".git",
    ".claude",
    "node_modules",
    "build",
    "dist",
    "site",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    ".eggs",
}
OUTPUT = Path(".claude/docs/CODE_MAP.md")


def first_line(doc: str | None) -> str:
    """First non-empty line of a docstring, trimmed — or '' if there is none."""
    if not doc:
        return ""
    for line in doc.strip().splitlines():
        if line.strip():
            return line.strip()
    return ""


def summarize_file(path: Path, root: Path) -> str:
    """Markdown section for one module, or '' if it has nothing worth listing."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, UnicodeDecodeError):
        return ""

    rel = path.relative_to(root).as_posix()
    members: list[str] = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            if node.name.startswith("_"):
                continue  # public surface only
            kind = "class" if isinstance(node, ast.ClassDef) else "def"
            summary = first_line(ast.get_docstring(node))
            suffix = f" — {summary}" if summary else ""
            members.append(f"- `{kind} {node.name}`{suffix}")

    mod_doc = first_line(ast.get_docstring(tree))
    if not mod_doc and not members:
        return ""

    section = [f"### `{rel}`"]
    if mod_doc:
        section.append(f"\n{mod_doc}\n")
    section.extend(members)
    return "\n".join(section) + "\n"


def iter_py_files(root: Path):
    """Yield every project ``.py`` file under *root*, skipping vendor/cache dirs."""
    for path in sorted(root.rglob("*.py")):
        if any(part in SKIP_DIRS for part in path.relative_to(root).parts):
            continue
        yield path


def main(argv: list[str]) -> int:
    """Write the code map and report the module count.

    Scan root precedence: an explicit ``argv[1]``; else ``src/`` when it exists
    (the common package layout — keeps the map to real source); else cwd.
    """
    if len(argv) > 1:
        root = Path(argv[1]).resolve()
    else:
        src = Path("src")
        root = src.resolve() if src.is_dir() else Path.cwd()
    sections = [s for s in (summarize_file(p, root) for p in iter_py_files(root)) if s]

    body = [
        "# Code map",
        "",
        "Generated by `.claude/scripts/gen_code_map.py` — what each module does,",
        "at a glance. **Read this before grepping the tree.** Regenerate after",
        "public-API changes (`just code-map`). Do not hand-edit.",
        "",
        *sections,
    ]
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(body).rstrip() + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT} ({len(sections)} modules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
