#!/usr/bin/env python3
"""Derive ``.github/CODEOWNERS`` from the protected-paths register.

An approval gate reads ``.agents/ship.conf`` and the register it names
(``glob<TAB>class<TAB>reason``): a PR touching a protected path waits for the
maintainer, any other PR may merge unattended once its required checks are
green. CODEOWNERS asks GitHub for the same review, so it is generated from the
register rather than kept by hand, and ``--check`` fails when it is stale.

    uv run python .agents/scripts/gen_codeowners.py --print    the file on stdout
    uv run python .agents/scripts/gen_codeowners.py --check    exit 1 when .github/CODEOWNERS differs
    uv run python .agents/scripts/gen_codeowners.py --write    rewrite it

The owner is the owner of the repo ``.agents/ship.conf`` names. Always owned,
whatever the register says: the register, the manifest and ``.github/``. Globs
are matched as the gate matches them: ``**`` crosses directories, ``*`` and
``?`` do not, case-insensitively. GitHub matches CODEOWNERS case-sensitively.
Stdlib only.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ".agents/ship.conf"
DEFAULT_REGISTER = ".agents/protected-paths.tsv"
OUT = ".github/CODEOWNERS"
# CODEOWNERS cannot express these, and the gate would read them differently.
_UNSUPPORTED = re.compile(r"[!\[\]\\\s]")


def manifest_value(root: Path, key: str) -> str:
    """Return the first value of ``key`` in the manifest, or ``""``."""
    path = root / MANIFEST
    if not path.is_file():
        return ""
    for line in path.read_text(encoding="utf-8").splitlines():
        line = re.sub(r"(^|[ \t])#.*", "", line).strip()
        parts = line.split(None, 1)
        if len(parts) == 2 and parts[0] == key:
            return parts[1].strip()
    return ""


def register_path(root: Path) -> str:
    """Return the register's repo-relative path, as the manifest names it."""
    return manifest_value(root, "protected") or DEFAULT_REGISTER


def read_rows(root: Path) -> list[tuple[str, str, str]]:
    """Return the register's ``(glob, class, reason)`` rows; raise on a malformed one."""
    rows: list[tuple[str, str, str]] = []
    rel = register_path(root)
    text = (root / rel).read_text(encoding="utf-8")
    for n, line in enumerate(text.splitlines(), 1):
        if not line.strip() or line.startswith("#"):
            continue
        fields = line.split("\t")
        if fields[0] == "glob":
            continue
        if len(fields) != 3 or not all(f.strip() for f in fields):
            raise ValueError(f"{rel}:{n}: want glob<TAB>class<TAB>reason, got {line!r}")
        if _UNSUPPORTED.search(fields[0]) or fields[0].startswith("/"):
            raise ValueError(f"{rel}:{n}: glob {fields[0]!r} cannot be written to CODEOWNERS")
        rows.append((fields[0], fields[1], fields[2]))
    return rows


def always_protected(root: Path) -> list[str]:
    """Return the globs every repo protects whatever its register says."""
    return [register_path(root), MANIFEST, ".github/**"]


def glob_regex(glob: str) -> re.Pattern[str]:
    """Translate a register glob to the regex the gate matches it with."""
    out = []
    i = 0
    while i < len(glob):
        if glob.startswith("**", i):
            out.append(".*")
            i += 2
            continue
        c = glob[i]
        out.append("[^/]*" if c == "*" else "[^/]" if c == "?" else re.escape(c))
        i += 1
    return re.compile("^" + "".join(out) + "$", re.IGNORECASE)


def is_protected(root: Path, path: str) -> bool:
    """Return whether the gate would hold ``path`` for the maintainer."""
    globs = [g for g, _, _ in read_rows(root)] + always_protected(root)
    return any(glob_regex(g).match(path) for g in globs)


def render(root: Path) -> str:
    """Return the CODEOWNERS text derived from the register."""
    repo = manifest_value(root, "repo")
    if not re.fullmatch(r"[^/\s]+/[^/\s]+", repo):
        raise ValueError(f"{MANIFEST} names no repo (want: repo <owner>/<name>)")
    owner = "@" + repo.split("/", 1)[0]
    lines = [
        f"# GENERATED by .agents/scripts/gen_codeowners.py from {register_path(root)}. Do not edit:",
        "# change the register, then run: uv run python .agents/scripts/gen_codeowners.py --write",
    ]
    seen: set[str] = set()
    for glob, _, _ in read_rows(root):
        if glob not in seen:
            seen.add(glob)
            lines.append(f"/{glob} {owner}")
    lines += [f"/{p} {owner}" for p in (register_path(root), MANIFEST, ".github/")]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    """Run the CLI; return the exit code."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--print", dest="mode", action="store_const", const="print")
    mode.add_argument("--check", dest="mode", action="store_const", const="check")
    mode.add_argument("--write", dest="mode", action="store_const", const="write")
    parser.add_argument("--root", type=Path, default=ROOT, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    try:
        new = render(args.root)
    except (OSError, ValueError) as exc:
        print(f"gen_codeowners: {exc}", file=sys.stderr)
        return 1
    out = args.root / OUT
    if args.mode == "print":
        sys.stdout.write(new)
        return 0
    if args.mode == "check":
        if out.is_file() and out.read_text(encoding="utf-8") == new:
            return 0
        print(f"gen_codeowners: {OUT} is missing or stale; run --write", file=sys.stderr)
        return 1
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(new, encoding="utf-8")
    print(f"gen_codeowners: wrote {len(new.splitlines()) - 2} rules to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
